CREATE TABLE IF NOT EXISTS users(
    id INTEGER PRIMARY KEY autoincrement,
    email VARCHAR(100) NOT NULL,
    senha VARCHAR(50) NOT NULL,
    nome VARCHAR(100) NOT NULL,
    status BOOLEAN DEFAULT TRUE,
    created TIMESTAMP DEFAULT (DATETIME(CURRENT_TIMESTAMP, '-3 hours')),
    modified TIMESTAMP DEFAULT (DATETIME(CURRENT_TIMESTAMP, '-3 hours'))
);